---
- name: diff maps of primary with secundary
  hosts: slaves
  become: true

  tasks:

    - name: copy template validateMaps.sh
      ansible.builtin.template:
        src: template/validateMaps.sh.j2
        dest: /usr/local/bin/validateMaps.sh
        owner: root
        group: wheel
        mode: '0644'

    - name: jub run as root compare and validade maps
      ansible.builtin.cron:
        name: compare and validade maps nis
        weekday: "*"
        minute: "*/25"
        hour: "*"
        user: root
        job: "/usr/bin/bash /usr/local/bin/validateMaps.sh"
...
